spring:
  datasource:
    #    url: jdbc:mariadb://mariadb:58806/integration_idm_2024?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    url: jdbc:mariadb://mariadb:3306/integration_idm_2024?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: jsolwpdlthffntus750!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

catalog:
  config:
    mcall: integration_mcall
    idm: integration_idm
    auth: integration_auth

custom:
  api-url:
    #    mcall: https://api-mcall.j-sol.co.kr
    #    idm: https://api-idm.j-sol.co.kr
    #    auth: https://api-auth.j-sol.co.kr
    auth: http://localhost:11001
    mcall: http://localhost:11201
    idm: http://localhost:11301

secret-key: kGU3Ss72dpWehaSOeFcHuhmYnp80KZbGx2QTcWhBueYCDNovsEzE2jGsYXfqaTyy5MgK3y1XBHhJzeMQsXnrYkYPWnH


file:
  mode: local
  #미디어 저장 디렉터리
  dir: /files/idm
