spring:
  datasource:
    #    url: jdbc:mariadb://210.97.108.4:58806/integration_mcall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    #    username: jsolution_developer
    #    password: wpdlthffntus750jsolution750
    url: jdbc:mariadb://localhost:3306/integration_mcall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      # idm 테이블은 데이터가 fk로 묶여있기 때문에 재생성 되지 않는다. auth는 재생성된다...
      # create 보단 update 설정 후 직접 mcall 테이블을 drop 하는게 편해보임.
      ddl-auto: update
#    driver-class-name: com.mysql.jdbc.Driver # com.mysql.jdbc.Driver deprecated
#    url: jdbc:mariadb://14.45.108.75:3306/mcall_edu
#    username: mcallroot
#    password: jsolwpdlthffntus750!@
#    driver-class-name: org.mariadb.jdbc.Driver

param:
  idm:
    #    url: http://localhost:3001/api/inout
    url: https://m-call.kro.kr/test/idm
  auth:
    #    url: http://172.17.0.1:8088/api
    url: http://210.97.108.4:8088/api

catalog:
  config:
    idm: integration_idm
    auth: integration_auth

