spring:
  datasource:

    ### docker 컨테이너 배포환경 전, localhost로 접근이 가능하다.
    #    url: jdbc:mariadb://localhost:58806/integration_mcall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"

    ### docker container 배포환경, docker host 설정
    url: jdbc:mariadb://mariadb:3306/integration_mcall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull&validationQuery="select 1"
    username: integration
    password: jsolwpdlthffntus750!@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

param:
  idm:
    #    url: http://localhost:3001/api/inout
    url: http://172.17.0.1:3001/api/inout
  auth:
    #    url: http://210.97.108.4:8088/api
    url: http://172.17.0.1:8088/api

catalog:
  config:
    idm: integration_idm
    auth: integration_auth

file:
  dir: /var/jenkins_home/workspace/MCall-shop/MCall-shop-backend/src/main/resources/models

media:
  dir: /var/jenkins_home/workspace/MCall-shop/MCall-shop-backend/src/main/resources/models/
