spring:
  datasource:
    #    url: jdbc:mariadb://210.97.108.4:58806/integration_mcall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    #    username: jsolution_developer
    #    password: wpdlthffntus750jsolution750
    url: jdbc:mariadb://localhost:12306/integration_idm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&userSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # idm 테이블은 데이터가 fk로 묶여있기 때문에 재생성 되지 않는다. auth는 재생성된다...
      # create 보단 update 설정 후 직접 mcall 테이블을 drop 하는게 편해보임.
      ddl-auto: update
    show-sql: true

#    driver-class-name: com.mysql.jdbc.Driver # com.mysql.jdbc.Driver deprecated
#    url: jdbc:mariadb://14.45.108.75:3306/mcall_edu
#    username: mcallroot
#    password: jsolwpdlthffntus750!@
#    driver-class-name: org.mariadb.jdbc.Driver


catalog:
  config:
    mcall: integration_mcall
    idm: integration_idm
    auth: integration_auth

secret-key: kGU3Ss72dpWehaSOeFcHuhmYnp80KZbGx2QTcWhBueYCDNovsEzE2jGsYXfqaTyy5MgK3y1XBHhJzeMQsXnrYkYPWnH

custom:
  api-url:
    mcall: https://api-mcall.j-sol.co.kr
    idm: https://api-idm.j-sol.co.kr
    auth: https://api-auth.j-sol.co.kr
#    auth: http://localhost:11001
#    mcall: http://localhost:11201
#    idm: http://localhost:11301


file:
  dir: /Users/leeseongbok/workspace/Github/IDM-BACKEND/src/main/resources/models

media:
  dir: /Users/leeseongbok/workspace/Github/IDM-BACKEND/api/src/main/resources/models

