server:
  port: 11402
  servlet:
    #    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
  tomcat:
    accesslog:
      directory: log
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 14
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"' #combined
      prefix: access
      rotate: true
      suffix: .log
    basedir: ./logs

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    persist-authorization: true
    display-request-duration: true
